Repository plan-player-analytics/Plan, pull requests merged in 2019-10, with the labels that each got.

#1179 Extensions Caller change
  Plan/common/src/main/java/com/djrapitops/plan/extension/ExtensionServiceImplementation.java
  Plan/common/src/main/java/com/djrapitops/plan/extension/implementation/CallerImplementation.java
  Plan/extensions/build.gradle
Labels: Bug

#1180 Removed comment from Webserver.Disable_Webserver
  Plan/common/src/main/java/com/djrapitops/plan/settings/config/changes/ConfigChange.java
  Plan/common/src/main/java/com/djrapitops/plan/settings/config/changes/ConfigUpdater.java
  Plan/common/src/main/resources/assets/plan/bungeeconfig.yml
  Plan/common/src/main/resources/assets/plan/config.yml
Labels: Enhancement

#1208 Allow Plan config directory to be a symlink
  Plan/common/src/main/java/com/djrapitops/plan/settings/config/ConfigWriter.java
Labels: Enhancement, status: Reviewed
